const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Steamworks_Ext,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.shadowlight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Steamworks_Ext.Acts.UnlockAchievement,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Particles.Cnds.IsSpraying,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareY
	];
};
self.C3_JsPropNameTable = [
	{MOVdisp: 0},
	{isattak: 0},
	{globalon: 0},
	{dashdisp: 0},
	{airtk: 0},
	{atkseq: 0},
	{combatk: 0},
	{fallspeed: 0},
	{Hitting: 0},
	{Blok: 0},
	{dead: 0},
	{Platform: 0},
	{Flash: 0},
	{Tween: 0},
	{smallStep: 0},
	{Ladia: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{Mode: 0},
	{Motor: 0},
	{MotorX: 0},
	{MotorY: 0},
	{Focus: 0},
	{FocusX: 0},
	{FocusY: 0},
	{HasFocus: 0},
	{zoom: 0},
	{ScrollTo: 0},
	{cam: 0},
	{Keyboard: 0},
	{IsGettinHit: 0},
	{Action: 0},
	{RandomVal: 0},
	{Resting: 0},
	{Isattakin: 0},
	{parryProgress: 0},
	{Onbattle: 0},
	{Pravda: 0},
	{Mouse: 0},
	{niceParticles: 0},
	{TiledBackground2: 0},
	{var: 0},
	{Info: 0},
	{instant_Info: 0},
	{BlockParticles: 0},
	{Buldges: 0},
	{BlockParticles2: 0},
	{Circle: 0},
	{BlockParticles3: 0},
	{Sine: 0},
	{FancyText: 0},
	{BlackScreen: 0},
	{Destructoid: 0},
	{TiledBackground3: 0},
	{SteamworksWebView2: 0},
	{MiscSprite: 0},
	{Bullet: 0},
	{PearBulleet: 0},
	{smokedust_small: 0},
	{ArenaBg: 0},
	{ArenaBg2: 0},
	{Alphariel: 0},
	{Alphariel_Text: 0},
	{Audio: 0},
	{bloodrain1: 0},
	{bloodrain2: 0},
	{blutspire: 0},
	{bloodrain3: 0},
	{Browser: 0},
	{luz1: 0},
	{ShadowLight: 0},
	{luz2: 0},
	{thingToDo: 0},
	{larten: 0},
	{luz3: 0},
	{hudCounter: 0},
	{Projectiles: 0},
	{Obstacles: 0},
	{tries: 0},
	{firstBattle: 0},
	{HUdCounter: 0},
	{fastrespawn: 0}
];

self.InstanceType = {
	Ladia: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	cam: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pravda: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	niceParticles: class extends self.IParticlesInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Info: class extends self.ITextInstance {},
	instant_Info: class extends self.ITextInstance {},
	BlockParticles: class extends self.IParticlesInstance {},
	Buldges: class extends self.ISpriteInstance {},
	BlockParticles2: class extends self.IParticlesInstance {},
	Circle: class extends self.ISpriteInstance {},
	BlockParticles3: class extends self.IParticlesInstance {},
	FancyText: class extends self.ITextInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	Destructoid: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	SteamworksWebView2: class extends self.IInstance {},
	MiscSprite: class extends self.ISpriteInstance {},
	PearBulleet: class extends self.ISpriteInstance {},
	smokedust_small: class extends self.IParticlesInstance {},
	ArenaBg: class extends self.ITiledBackgroundInstance {},
	ArenaBg2: class extends self.ITiledBackgroundInstance {},
	Alphariel: class extends self.ISpriteInstance {},
	Alphariel_Text: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	bloodrain1: class extends self.IParticlesInstance {},
	bloodrain2: class extends self.IParticlesInstance {},
	blutspire: class extends self.ISpriteInstance {},
	bloodrain3: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	luz1: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	luz2: class extends self.ISpriteInstance {},
	larten: class extends self.ISpriteInstance {},
	luz3: class extends self.ISpriteInstance {},
	hudCounter: class extends self.ITextInstance {},
	Projectiles: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {}
}