name: Build Blog Index

on:
  push:
    branches:
      - main  # change to "master" if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run build script
        run: python build_blog.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/index.html
          git commit -m "Auto-update blog index" || echo "No changes to commit"
          git push
